title: Joy Flowers (PhD Student, The Pennsylvania State University)
logo: /assets/img/Prof_pic_cropped.png
description: A condensed resume documenting major academic and professional experiences
show_downloads: true
theme: jekyll-theme-slate
